verbose: True
dataset: 'scannet'

stride: 1
only_tracking: False
setting: demo

mapping:
  BA: False
  BA_cam_lr: 0.001
  use_mono_to_complete: True
  pixels: 2000
  iters_first: 500
  geo_iter_first: 200
  iters: 300

tracking:
  buffer: 512
  beta: 0.75
  warmup: 12
  mono_thres: 0.05
  max_age: 50
  motion_filter:
    thresh: 4.0  
  multiview_filter:
    thresh: 0.03  
    visible_num: 2  
  frontend:
    enable_loop: True
    enable_online_ba: True
    keyframe_thresh: 4.0  
    thresh: 16.0  
    window: 50  
    radius: 2
    nms: 0
    max_factors: 100  
  backend:
    thresh: 25.0 
    radius: 1
    nms: 5
    # used for loop detection
    loop_window: 50
    loop_thresh: 25.0
    loop_radius: 1
    loop_nms: 25
    BA_type: "DSPO"

cam:
  ### original camera parameters
  H: 480
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000.0 #for depth image in png format
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 8
  W_edge: 16
  H_out: 240
  W_out: 320

pointcloud:
  radius_add_max: 0.08 
  radius_add_min: 0.02

mono_prior:
  depth: omnidata
  depth_pretrained: ./pretrained/omnidata_dpt_depth_v2.ckpt
  predict_online: True

data:
  output: /cluster/work/cvl/esandstroem/src/mono_point_slam/output/Scannet

