inherit_from: ./configs/Scannet/scannet.yaml


scene: scene0106
only_tracking: False
wandb: True
max_frames: -1

meshing:
  gt_mesh_path: /cluster/work/cvl/esandstroem/src/mono_point_slam/scans/scene0106_00/scene0106_00_vh_clean_2.ply

data:
  input_folder: datasets/Scannet/scene0106_00