inherit_from: configs/Replica/replica.yaml
scene: demo_office0
only_tracking: False
wandb: False
stride: 2
max_frames: 200

mono_prior:
  depth: omnidata
  depth_pretrained: ./pretrained/omnidata_dpt_depth_v2.ckpt
  predict_online: True

mapping:
  iters: 200

tracking:
  backend:
    ba_freq: 20

setting: demo

meshing:
  gt_mesh_path: cull_replica_mesh/office0.ply
data:
  output: output/Replica
  input_folder: datasets/Replica/office0