inherit_from: configs/Replica/replica.yaml
scene: office4
only_tracking: False
wandb: True
tracking:
  frontend:
    keyframe_thresh: 2.75 

meshing:
  gt_mesh_path: cull_replica_mesh/office4.ply
data:
  input_folder: datasets/Replica/office4