inherit_from: configs/Replica/replica.yaml

scene: room1
only_tracking: False
wandb: True

tracking:
  buffer: 300
  frontend:
    keyframe_thresh: 2.75  

meshing:
  gt_mesh_path: cull_replica_mesh/room1.ply
data:
  input_folder: datasets/Replica/room1
  # input_folder: ${TMPDIR}/room1