inherit_from: ./configs/VIVID/vivid.yaml
scene: outdoor_robust_day1
only_tracking: False
offline_mapping: False
offline_video: video.npz
wandb: False

stride: 2
max_frames: -1

mapping:
  iters: 150

setting: demo

data:
  input_folder: datasets/vividpp/outdoor_robust_day1
  modality: thermal

cam:  #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 464
  W: 632
  fx: 327.40890654
  fy: 328.90888448
  cx: 317.55620197
  cy: 231.37528736
